### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by whiteorchid** [jphe/scTE#5]
Hi,

According to the manual, it seems in the final or intermediate step, there came out an error `TypeError: '<' not supported between instances of 'str' and 'int' ,` do you have any ideas about this, thanks a lot!

Best,

**Comment by jphe** [comment]
Hi，

Can you give more details about what's the error is, in the log file it should report which line casued this error, just paste the log file.

And what's the command you use?

**Comment by whiteorchid** [comment]
```
1', '2332', '1306', '2184', '2232', '1539', '87', '829', '1686', '23', '2394', '1273', '742', '664', '91', '2127', '1808', '2326', '2408', '2029', '2260', '649', '1714', '762', '1851', '855', '1358', '1153', '2377', '1174', '154', '711', '1445', '2133', '1402', '228', '165', '1860']
Traceback (most recent call last):
  File "/users/s/g/sg/.conda/envs/tophat/bin/scTE", line 4, in <module>
    __import__('pkg_resources').run_script('scTE==1.0', 'scTE')
  File "/users/s/g/sg/.conda/envs/tophat/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/users/s/g/sg/.conda/envs/tophat/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/gpfs1/home/s/g/sg/.conda/envs/tophat/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE", line 168, in <module>
    main()
  File "/gpfs1/home/s/g/sg/.conda/envs/tophat/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/EGG-INFO/scripts/scTE", line 154, in main
    len_res, genenumber, filename = Countexpression(filename=args.out, allelement=allelement, genenumber=args.genenumber, cellnumber=args.cellnumber, hdf5=args.hdf5)
  File "/users/s/g/sg/.conda/envs/tophat/lib/python3.8/site-packages/scTE-1.0-py3.8.egg/scTE/base.py", line 416, in Countexpression
    gene_seen.sort()
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by whiteorchid** [comment]
source activate tophat

`scTE -i Parent_NGSC3_DI_PBMC_possorted_genome_bam.bam -o test1 -g hg38 -x hg38.inclusive.idx --keeptmp True  `

**Comment by jphe** [comment]
It seems your reference "hg38.inclusive.idx" file is wrong, in the gene name column it has both integer and string types, while all the gene name should be string.

You can check by runing this:
```
from scTE.miniglbase import genelist, glload, location

anno = glload('hg38.inclusive.idx')
allelement = set(anno['annot'])
wrong_genes = [ k for k in allelement if isinstance(k,int) ]
print(wrong_genes)
```

Besides, your chromosome name is incorrect, you have chrosome named [ '2332', '1306', '2184', '2232', '1539' ...], no such chromosome in human genome.

How did you generate the 'hg38.inclusive.idx' file ?

**Comment by whiteorchid** [comment]
Thanks!
I generated the idx file by first download the gene gtf file and the rmsk TE file, then `scTE_build -g hg38 -m inclusive -te rmsk.txt -gene gencode.v30.annotation.gtf`, as by the manual scTE_build -g hg38, there seems error in the log file, 
```
--2020-10-03 12:50:59--  http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

INFO    : Saved binary version of list: 'hg38.exclusive.idx'
INFO    : Done genome annotation index building... 2020-10-03 12:58:37
Done the index building, results output to hg38.exclusive.idx 
```

**Comment by whiteorchid** [comment]
```
--2020-10-04 14:56:21--  http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

INFO    : genelist(): loaded 'rmsk.txt.gz' found 5607738 items
INFO    : Saved binary version of list: 'hg38.inclusive.idx'
INFO    : Done genome annotation index building... 2020-10-04 15:11:26
Done the index building, results output to hg38.inclusive.idx 

676M Oct  4 15:10 hg38.inclusive.idx


```

Use scTE_build will generate a idx file near 676M, not sure if it's complete. Manually(-te -gene) will generate 729M idx file.

**Comment by whiteorchid** [comment]
I guess it's in build step, I forgot to convert the rmsk file to bed format. Thanks a lot!

**Comment by jphe** [comment]
Yes, you need convert the rmsk file into 6 columbs bed format first.

or you can just run 'scTE_build -g hg38' if you node is internet accessible, it will downlaod the rmsk and gtf file and generate the idx automatically.

**Comment by whiteorchid** [comment]
OK. Got it. Thanks so much for your kind help and guidance!

**Comment by whiteorchid** [comment]
Hi,

May I know the file size of the` hg38.inclusive.idx` you generated, our compute node not connect to the net, so manually generate the hg38 idx file, 892M in size. Also is it  convenient to share the column number of the results file for the hg38(inclusive) test, does it equals the number of genes plus the TEs, thanks a lot!

Best,

**Comment by jphe** [comment]
In the hg38.exclusive.idx file (608M) it has 58147 elements (Genes+TEs). This number will vary depends the gtf file you use, as the gene number may has some difference for different gtf file.

By default, scTE only keep the LINE|SINE|LTR|DNA|Retroposon elements, so you need to clean other elements in the rmsk file if you generate the idx by hand. 

```
676M  hg38.inclusive.idx
608M  hg38.exclusive.idx
```

**Comment by whiteorchid** [comment]
Thanks a lot!

By the way, use the hg38.inclusive.idx file (676M) which use another server, by `scTE_build  -g hg38 -m inclusive`, got the results, and the first line contains 58389 elements. 

May I know is it possible to only make the index of the TEs or only get the results of the TEs, so it may be more clear to tell the TEs in the heatmap and other figures. As checking the first line of the results using hg38.inclusive.idx, it seems the names are all gene names. So which item belongs to the TEs seems not easy to tell.

Thanks for your kind guidance!

Best,
